# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_saled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ListContent', models.CharField(max_length=50)),
            ],
        ),
    ]
